import { Inter } from "next/font/google";
import NavBar from "@/components/navBar";
import "@/app/globals.css";
import { getSession } from "@/lib/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const checkLogin = async () => {
        const session = await getSession();
        console.log(session);

        if (session != null) {
            return true;
        } else {
            return false;
        }
    };

    return (
        <html>
            <body className={inter.className}>
                <NavBar logged={await checkLogin()} />
                {children}
            </body>
        </html>
    );
}
